name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region


    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
          echo "::set-output name=dir::$(yarn cache dir)"
          echo "::set-output name=version::$(yarn -v)"

    - name: Save cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}

        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-


    - name: Install dependencies
      run: |
        yarn --production --frozen-lockfile --non-interactive

    - name: Build 
      run: |
          yarn build


    - name: Zip project files
      run: |
        zip -r app.zip * .[^.]*

    - name: Upload to S3
      env:
        AWS_REGION: us-east-1  # Change to your AWS region
        S3_BUCKET: duner-bucket-2024  # Change to your S3 bucket name
      run: |
        aws s3 cp app.zip s3://$S3_BUCKET/app.zip

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_REGION: us-east-1  # Change to your AWS region
        APPLICATION_NAME: beta-app-duner  # Change to your Elastic Beanstalk application name
        ENVIRONMENT_NAME: Beta-app-duner-env  # Change to your Elastic Beanstalk environment name
      run: |
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $(date +%Y%m%d%H%M%S) --source-bundle S3Bucket=$S3_BUCKET,S3Key=app.zip
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $(date +%Y%m%d%H%M%S)